language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

stages:
  - build

env:
  global:
    - BASE_NAME=10-bitClockWidget
    - secure: "jAX8B77IaVA22mzVmrtIcmKbvaVmY1v26fo6zU7Po6u0kv9riUKpDIr/dh6rC2C7icZj5NXomiX8voqhso0htQLiW8+PsIMG5Se8dn2Fauw3PJUVa3/LO9KwTQWJ2OFRtmAXqgrqY0JR7Wopmh+UY6ALZ/G3kecC6jGQRsQqNOEfW3meVs2FmCFNbYrtP4oBB2fHovDEavyhWcLPchlmwA+YrMQEjRHZbiSpI7V8jsOQGrNwK/SP+UXDoV2m1dx9GefHMmwMJfWJK2bpAk1SDX687rrd/bXowYc+i+arma6Gu9rBJgTZzEk0zd0AcdeWb9C23xsYeezZaDRE8xaALu9//K+hWzrO74fUYPFoBaGt4rwjqHrV1ChHzWxwFiEHkLkIG5Z9N8lDp9E95Wy58D1ZMJxoASPBNentq/xocQ+rD7qPTSx3tHDCGOv89W+CVXWMwcb6MyQU8T7BoI5OxRago+Csvk72bPKfXBpQn033gx4GlKnCs6DkinEtYvqbyTBmN6wnW4jlhE69/1EGxdbvmsBaY2kMp8+4gTxw2Jt34Z1rgNoOgNCE0iJiyhEaXdElOA/JCisovwHnUOBGFVaz9Mj5mQaM09eE+nDehMtTH006LTcXtdEZV84CFce5z0uZIBPu5xxniwYrF3SzpFGHDyE7p+FC62r9I9DsgWI="
    - secure: "SS12DpePosXuuSe9F7aFOGrNkTdjFkgdAP6cvX5XRUl3qZb6DFPZr7wTyVViNhuaDYuMoU/4uA8zdOxn5AWZ6NmlB0FOGJjWwvJsOVKi7pyXel8bZ++96iIGOXgD6lJ15ThHe3BZabzLkAjwmHCUAijdw5cPuXo6QYpsKf7+7SMGrarq6EPF4VxnwkXZ2RYBWREYuCpVjT3TbiFOoxteFIfd+fHUZ6M3sM2s0bnsqAp47Z11DdUuhxHIDo8Pw6IzXaROg/ZOW7SoW00uVeK1Nb5rYxJ4GMlROu3XL4mIt73wiGJGVMdynRAqI1Lg6/BCkSaXVm3hu/CU6uvrJV+kBifQakvwoe4Qqvp5HPD6trUIOcRiY0BhXKVVp3z5AB6rQkaIqfLmS/H2r0j2JdCEpHFaOtNZ32v/r/OH5d1Vffxz2hqgCX6/wo+LuSElx5Szvpdjxc3qLgi8uSGELFcznaGpEMH8RoBjACvINwZiPqygLAAIps8IpYyBy8QJDymI0hFlGtnhiZZZ5xRuqsEr1JSt1TgUeo4jJoxFkSdZy6yQaahLIWk9g6mpGcklpWxlkiiJQYoAmKoiBq+L9NRejrGjxEMv2KV53/uhJxXbGb4n/UO5NN90UVXBsvJAtrr+wIFJqrwNKXjLYUhNdgfp2XwqfdRr7sNfQ5rHH+V2WIA="

jobs:
  include:
    - stage: build
      before_script:
        - openssl aes-256-cbc -K $encrypted_1edfc004dbae_key -iv $encrypted_1edfc004dbae_iv -in keystore.jks.enc -out "$BASE_NAME/keystore.jks" -d
        - cd "$BASE_NAME"
      script:
        - ./gradlew assembleRelease
        - mv "app/build/outputs/apk/release/$BASE_NAME-release-unsigned.apk" .
        - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass "$STORE_PASS" -keypass "$KEY_PASS" "$BASE_NAME-release-unsigned.apk" default
        - jarsigner -verify "$BASE_NAME-release-unsigned.apk"
        - $ANDROID_HOME/build-tools/28.0.3/zipalign -v 4 "$BASE_NAME-release-unsigned.apk" "$BASE_NAME-release.apk"
      after_script:
        - rm -f keystore.jks
      deploy:
        provider: releases
        file: "$BASE_NAME-release.apk"
        skip_cleanup: true
        on:
          repo: "ashutoshgngwr/$BASE_NAME"
          tags: true
        api_key:
          secure: "ASnunNsi1pcgyLYqZbaes9cOBjBl9mvgWX5uDvp9b8p1QfUTYLwB5HM9giqEzv5xBozKXrmH1WJI+9bb8mCeGLkibKxHsQglML+iwjg5EVRvPnI5D7AwZO4RSZSBFULLaLUkl2QHXtlnwxJB32CGFh1o6sxkOSKpiMPm/hVhuDYwGNCqSQVJoAgxnwCK5v7DgegJI94dlhJ8wv1rO2dNpAgSkd3B/CNmHyfUjdKdrRGFJ14v+jSVy5+Iq65Uv5haB0G64lPqEUcHUKmKriOj2I4+Vp2H55HRPizRuWm1+tRybs0jcGLlN5oc67fTu/yvEPoAm5ZRUbNnM2jo2HTlod1r5dXIo897YiuvBL3N3p/ANeRO1OVmWh1iCtO9fh5Vvz5yn8QPIIis3vMlKQ2hlEbx/G21FPS48txGf1tt0eNXBcqQnwVpv+Kz8C+Z+4fkR3ifAjVEzeafrfjiqRZhuTUOoh/P33nkcPkC9XE1uFk4xDZa3ZVm7jyzF1dwBSl4Z+J77XHeCE/vVqg/YJ55fXjeXbjfVFcUEFjoX3PTsb893fZJd4G6xEeiN07+2LIYejM3dlVp+V/svBgE3KGRjul0CkXfZFAFJxb6EZII/FeUcnKZd1BlGkSzvDtfNVyuU5Cr66hVL0Ld60ZjKxWyRNvOpWHSghNUD6hJX48nccI="
